---
title: "Quarto-Training"
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
editor: visual
execute:
  warning: false
---

# Introduction

This guide has been written for you to follow along, you will create your own version of this file as you go. It will work best if you have two screens - have this document open on one screen, and R Studio with the code and output on the other (main) screen.

Before we go any further, copy the code below into your console and run it. This will identify and install any missing packages that are required for this script to run correctly.

```{r}

# If a package is installed, it will be loaded. If any 
# are not, the missing package(s) will be installed from CRAN

# First specify the packages of interest
packages = c("dplyr", "tidyr", "lubridate", "zoo",
             "ggplot2", "DT", "reactable", "plotly")

# Installs if required
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      }
  }
)

```

Start by opening the qmd file "quarto-dev.qmd" in R Studio. This is an unformatted version of the Quarto file that created this guide. You create the output by Render-ing it. Click the 'Render' button and look at the document it creates. How does it compare to this file? (The first time you render a qmd script you may receive warning messages about packages that are required but aren't yet installed. We have tried to pre-empt this by running the code above, but if it still happens install those packages and render again.)

As you work through this guide you will add formatting and content to your script until your rendered document looks like this one!

This guide does not go into the magic that happens between hitting the 'render' button and the output file being produced. There are plenty of resources on the internet if you want to explore this further. For more details about all things Quarto visit <http://quarto.org>.

This guide will start by looking at formatting your document, then will add in some data and charts, and improve how they look. The final section adds some interactivity to some of the charts.
